#############################################################################
# Makefile for building: 77x
# Generated by qmake (3.0) (Qt 5.4.1)
# Project:  77x.pro
# Template: app
# Command: D:\Soft\programming\qt-5.4.1\qtbase\bin\qmake.exe -o Makefile 77x.pro
#############################################################################

MAKEFILE      = Makefile

first: debug
install: debug-install
uninstall: debug-uninstall
QMAKE         = D:\Soft\programming\qt-5.4.1\qtbase\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = copy /y
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		debug \
		release


debug: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug uninstall
release: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release uninstall

Makefile: 77x.pro D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\win32-msvc2013\qmake.conf D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\features\spec_pre.prf \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\common\shell-win32.conf \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\qconfig.pri \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_lib_bootstrap_private.pri \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_lib_concurrent.pri \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_lib_concurrent_private.pri \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_lib_core.pri \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_lib_core_private.pri \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_lib_gui.pri \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_lib_gui_private.pri \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules-inst\qt_lib_multimedia.pri \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules-inst\qt_lib_multimedia_private.pri \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_lib_multimedia.pri \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules-inst\qt_lib_multimediawidgets.pri \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules-inst\qt_lib_multimediawidgets_private.pri \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_lib_multimediawidgets.pri \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_lib_network.pri \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_lib_network_private.pri \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_lib_opengl.pri \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_lib_opengl_private.pri \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_lib_openglextensions.pri \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_lib_openglextensions_private.pri \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_lib_platformsupport_private.pri \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_lib_printsupport.pri \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_lib_printsupport_private.pri \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_lib_sql.pri \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_lib_sql_private.pri \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_lib_testlib.pri \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_lib_testlib_private.pri \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_lib_widgets.pri \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_lib_widgets_private.pri \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_lib_xml.pri \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_lib_xml_private.pri \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_plugin_qgenericbearer.pri \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_plugin_qico.pri \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_plugin_qminimal.pri \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_plugin_qnativewifibearer.pri \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_plugin_qoffscreen.pri \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_plugin_qtaudio_windows.pri \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_plugin_qtmedia_audioengine.pri \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_plugin_qtmultimedia_m3u.pri \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_plugin_qwindows.pri \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_plugin_windowsprintersupport.pri \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_tool_qdoc.pri \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_tool_qlalr.pri \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_tool_syncqt.pri \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_tool_uic.pri \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\features\qt_functions.prf \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\features\qt_config.prf \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\features\win32\qt_config.prf \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\win32-msvc2013\qmake.conf \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\features\spec_post.prf \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\features\exclusive_builds.prf \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\features\default_pre.prf \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\features\win32\default_pre.prf \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\features\resolve_config.prf \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\features\exclusive_builds_post.prf \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\features\default_post.prf \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\features\win32\rtti.prf \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\features\precompile_header.prf \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\features\warn_on.prf \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\features\qt.prf \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\features\resources.prf \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\features\moc.prf \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\features\win32\opengl.prf \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\features\uic.prf \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\features\win32\windows.prf \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\features\testcase_targets.prf \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\features\exceptions.prf \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\features\yacc.prf \
		D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\features\lex.prf \
		77x.pro \
		D:/Soft/programming/qt-5.4.1/qtbase/lib/qtmaind.prl \
		D:/Soft/programming/qt-5.4.1/qtbase/lib/Qt5Cored.prl \
		D:/Soft/programming/qt-5.4.1/qtbase/lib/Qt5MultimediaWidgets.prl \
		D:/Soft/programming/qt-5.4.1/qtbase/lib/Qt5Multimedia.prl \
		D:/Soft/programming/qt-5.4.1/qtbase/lib/Qt5Network.prl \
		D:/Soft/programming/qt-5.4.1/qtbase/lib/Qt5Core.prl \
		D:/Soft/programming/qt-5.4.1/qtbase/lib/Qt5Gui.prl \
		D:/Soft/programming/qt-5.4.1/qtbase/lib/qtharfbuzzng.prl \
		D:/Soft/programming/qt-5.4.1/qtbase/lib/Qt5Widgets.prl \
		D:/Soft/programming/qt-5.4.1/qtbase/lib/Qt5OpenGL.prl \
		D:/Soft/programming/qt-5.4.1/qtbase/lib/Qt5Xml.prl \
		D:/Soft/programming/qt-5.4.1/qtbase/plugins/mediaservice/qtmedia_audioengine.prl \
		D:/Soft/programming/qt-5.4.1/qtbase/plugins/audio/qtaudio_windows.prl \
		D:/Soft/programming/qt-5.4.1/qtbase/plugins/playlistformats/qtmultimedia_m3u.prl \
		D:/Soft/programming/qt-5.4.1/qtbase/plugins/platforms/qwindows.prl \
		D:/Soft/programming/qt-5.4.1/qtbase/lib/Qt5PlatformSupport.prl \
		D:/Soft/programming/qt-5.4.1/qtbase/plugins/imageformats/qico.prl \
		D:/Soft/programming/qt-5.4.1/qtbase/plugins/bearer/qgenericbearer.prl \
		D:/Soft/programming/qt-5.4.1/qtbase/plugins/bearer/qnativewifibearer.prl
	$(QMAKE) -o Makefile 77x.pro
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\features\spec_pre.prf:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\common\shell-win32.conf:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\qconfig.pri:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_lib_bootstrap_private.pri:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_lib_concurrent.pri:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_lib_concurrent_private.pri:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_lib_core.pri:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_lib_core_private.pri:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_lib_gui.pri:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_lib_gui_private.pri:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules-inst\qt_lib_multimedia.pri:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules-inst\qt_lib_multimedia_private.pri:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_lib_multimedia.pri:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules-inst\qt_lib_multimediawidgets.pri:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules-inst\qt_lib_multimediawidgets_private.pri:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_lib_multimediawidgets.pri:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_lib_network.pri:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_lib_network_private.pri:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_lib_opengl.pri:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_lib_opengl_private.pri:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_lib_openglextensions.pri:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_lib_openglextensions_private.pri:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_lib_platformsupport_private.pri:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_lib_printsupport.pri:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_lib_printsupport_private.pri:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_lib_sql.pri:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_lib_sql_private.pri:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_lib_testlib.pri:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_lib_testlib_private.pri:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_lib_widgets.pri:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_lib_widgets_private.pri:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_lib_xml.pri:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_lib_xml_private.pri:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_plugin_qgenericbearer.pri:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_plugin_qico.pri:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_plugin_qminimal.pri:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_plugin_qnativewifibearer.pri:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_plugin_qoffscreen.pri:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_plugin_qtaudio_windows.pri:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_plugin_qtmedia_audioengine.pri:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_plugin_qtmultimedia_m3u.pri:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_plugin_qwindows.pri:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_plugin_windowsprintersupport.pri:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_tool_qdoc.pri:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_tool_qlalr.pri:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_tool_syncqt.pri:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\modules\qt_tool_uic.pri:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\features\qt_functions.prf:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\features\qt_config.prf:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\features\win32\qt_config.prf:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\win32-msvc2013\qmake.conf:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\features\spec_post.prf:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\features\exclusive_builds.prf:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\features\default_pre.prf:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\features\win32\default_pre.prf:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\features\resolve_config.prf:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\features\exclusive_builds_post.prf:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\features\default_post.prf:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\features\win32\rtti.prf:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\features\precompile_header.prf:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\features\warn_on.prf:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\features\qt.prf:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\features\resources.prf:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\features\moc.prf:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\features\win32\opengl.prf:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\features\uic.prf:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\features\win32\windows.prf:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\features\testcase_targets.prf:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\features\exceptions.prf:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\features\yacc.prf:
D:\Soft\programming\qt-5.4.1\qtbase\mkspecs\features\lex.prf:
77x.pro:
D:/Soft/programming/qt-5.4.1/qtbase/lib/qtmaind.prl:
D:/Soft/programming/qt-5.4.1/qtbase/lib/Qt5Cored.prl:
D:/Soft/programming/qt-5.4.1/qtbase/lib/Qt5MultimediaWidgets.prl:
D:/Soft/programming/qt-5.4.1/qtbase/lib/Qt5Multimedia.prl:
D:/Soft/programming/qt-5.4.1/qtbase/lib/Qt5Network.prl:
D:/Soft/programming/qt-5.4.1/qtbase/lib/Qt5Core.prl:
D:/Soft/programming/qt-5.4.1/qtbase/lib/Qt5Gui.prl:
D:/Soft/programming/qt-5.4.1/qtbase/lib/qtharfbuzzng.prl:
D:/Soft/programming/qt-5.4.1/qtbase/lib/Qt5Widgets.prl:
D:/Soft/programming/qt-5.4.1/qtbase/lib/Qt5OpenGL.prl:
D:/Soft/programming/qt-5.4.1/qtbase/lib/Qt5Xml.prl:
D:/Soft/programming/qt-5.4.1/qtbase/plugins/mediaservice/qtmedia_audioengine.prl:
D:/Soft/programming/qt-5.4.1/qtbase/plugins/audio/qtaudio_windows.prl:
D:/Soft/programming/qt-5.4.1/qtbase/plugins/playlistformats/qtmultimedia_m3u.prl:
D:/Soft/programming/qt-5.4.1/qtbase/plugins/platforms/qwindows.prl:
D:/Soft/programming/qt-5.4.1/qtbase/lib/Qt5PlatformSupport.prl:
D:/Soft/programming/qt-5.4.1/qtbase/plugins/imageformats/qico.prl:
D:/Soft/programming/qt-5.4.1/qtbase/plugins/bearer/qgenericbearer.prl:
D:/Soft/programming/qt-5.4.1/qtbase/plugins/bearer/qnativewifibearer.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile 77x.pro

qmake_all: FORCE

make_first: debug-make_first release-make_first FORCE
all: debug-all release-all FORCE
clean: debug-clean release-clean FORCE
	-$(DEL_FILE) 77x.ilk
	-$(DEL_FILE) 77x.idb
distclean: debug-distclean release-distclean FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) C:\Users\Bill\Documents\Qt\77x\77x_plugin_import.cpp 77x.pdb

debug-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocclean
release-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocclean
mocclean: debug-mocclean release-mocclean

debug-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocables
release-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocables
mocables: debug-mocables release-mocables

check: first
FORCE:

$(MAKEFILE).Debug: Makefile
$(MAKEFILE).Release: Makefile
